<a href="https://colab.research.google.com/github/Roghiehghahremani/PyTorch-Codemy/blob/main/Tensor_OPs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [7]:
my_torch =  torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape and view

In [4]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch = my_torch.reshape(-1,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch3 = my_torch2.reshape(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch2[2] = 1212
my_torch2

tensor([   0,    1, 1212,    3,    4,    5,    6,    7,    8,    9])

In [15]:
my_torch3

tensor([[   0,    1, 1212,    3,    4],
        [   5,    6,    7,    8,    9]])

In [21]:
my_torch3[1,2] = 5656
my_torch3

tensor([[   0,    1, 1212,    3,    4],
        [   5,    6, 5656,    8,    9]])

In [22]:
my_torch2

tensor([   0,    1, 1212,    3,    4,    5,    6, 5656,    8,    9])

In [25]:
my_torch2[2].item()

1212